server:
  port: 8084

spring:
  application:
    name: springboot-elasticsearch

elasticsearch:
  schema: http
  uris:
    - 192.168.93.128:9200
  connectTimeout: 10000
  socketTimeout: 10000
  connectionRequestTimeout: 10000
  maxConnectNum: 100
  maxConnectPerRoute: 100